name: Build

on:
  push:
    branches:
      - main
      - dev
      - dev_flow
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: davevader/dare_test:3.2

    strategy:
        matrix:
            build: [Debug, Release]
            compiler: [{cc: gcc, cxx: g++, trilinos: trilinos_gcc}, {cc: clang-18, cxx: clang++-18, trilinos: trilinos_clang}]
        fail-fast: false

    steps:
    - name: https://github.com/actions/checkout/issues/1720
      run: |
        apt install -y acl
        setfacl -R -d -m u:ACTIONS_USER:rwx /home/ACTIONS_USER

    - uses: actions/checkout@v5

    - name: Configure CMake
      run: |
          rm -rf build
          mkdir build && cd build
          cmake .. -GNinja \
                   -DUSE_GTEST=OFF \
                   -DDEBUG=OFF \
                   -DCMAKE_BUILD_TYPE=${{matrix.build}} \
                   -DCMAKE_C_COMPILER=${{matrix.compiler.cc}} \
                   -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}} \
                   -DCMAKE_PREFIX_PATH=/usr/local/${{matrix.compiler.trilinos}}
          
    - name: Build
      run: |
          cd build
          ninja -j 4
