name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self_hosted
    container:
        image: davevader/dare_test:3.2

    strategy:
        matrix:
            build: [Debug, Release]
            compiler: [{cc: gcc, cxx: g++, trilinos: trilinos_gcc}, {cc: clang-18, cxx: clang++-18, trilinos: trilinos_clang}]
        fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
          rm -rf build
          mkdir build && cd build
          cmake .. -GNinja \
                   -GUSE_GTEST=OFF \
                   -DDEBUG=OFF \
                   -DCMAKE_BUILD_TYPE=${{matrix.build}} \
                   -DCMAKE_C_COMPILER=${{matrix.compiler.cc}} \
                   -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}} \
                   -DCMAKE_PREFIX_PATH=/usr/local/${{matrix.compiler.trilinos}}
          
    - name: Build
      run: |
          cd build
          ninja -j 4
