name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_gcc_release:
    runs-on: self-hosted
    container:
      image: davevader/dare_test:3.1

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake Release
      run: |
          mkdir build_gcc_release && cd build_gcc_release
          cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja -DUSE_GTEST=OFF -DDEBUG=OFF
          
    - name: Build Release
      run: |
          cd build_gcc_release
          ninja -j 4

  build_gcc_debug:
    runs-on: self-hosted
    container:
      image: davevader/dare_test:3.1

    steps:
    - name: Configure CMake Debug
      run: |
          mkdir build_gcc_debug && cd build_gcc_debug
          cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja -DUSE_GTEST=OFF -DDEBUG=ON
          
    - name: Build Debug
      run: |
          cd build_gcc_debug
          ninja -j 4

  build_clang_debug:
    runs-on: self-hosted
    container:
      image: davevader/dare_test:3.1

    steps:
    - name: Configure CMake Debug
      run: |
          mkdir build_clang_debug && cd build_clang_debug
          cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja -DUSE_GTEST=OFF -DDEBUG=ON -DCMAKE_C_COMPILER=clang-18 -DCMAKE_CXX_COMPILER=clang++-18
          
    - name: Build Debug
      run: |
          cd build_clang_debug
          ninja -j 4

  build_clang_release:
    runs-on: self-hosted
    container:
      image: davevader/dare_test:3.1

    steps:
    - name: Configure CMake Release
      run: |
          mkdir build_clang_release && cd build_clang_release
          cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja -DUSE_GTEST=OFF -DDEBUG=OFF -DCMAKE_C_COMPILER=clang-18 -DCMAKE_CXX_COMPILER=clang++-18
          
    - name: Build Release
      run: |
          cd build_clang_release
          ninja -j 4