name: Testing

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    
jobs:

  Serial:
    runs-on: wsl
    container:
      image: davevader/dare_test:1.0

    strategy:
      matrix:
        procs: [1, 2, 3, 4]
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake Test
      run: |
          mkdir build_test && cd build_test
          cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja -DUSE_GTEST=ON -DDEBUG=ON

    - name: Build Test
      run: |
          cd build_test
          ninja -j 4

    - name: Run Test
      run: |
          cd build_test
          mpirun -n ${{matrix.procs}} ./unit_test --gtest_output="xml:${pwd}Report_P${{matrix.procs}}.xml"
          mv *xml ../
          
    # - name: Run Test 2 Processes
    #   run: |
    #     cd build_test
    #     mpirun -n 2 ./unit_test --gtest_output="xml:${pwd}Report_P2.xml"
    #     mv *xml ../

    # - name: Run Test 3 Processes
    #   run: |
    #     cd build_test
    #     mpirun -n 3 ./unit_test --gtest_output="xml:${pwd}Report_P3.xml"
    #     mv *xml ../
        
    # - name: Run Test 4 Processes
    #   run: |
    #     cd build_test
    #     mpirun -n 4 ./unit_test --gtest_output="xml:${pwd}Report_P4.xml"
    #     mv *xml ../

    - name: Archive Testing Reports
      uses: actions/upload-artifact@v3
      with:
        name: test_reports_${{matrix.procs}}
        path: ./*.xml
