name: Testing

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    
jobs:

  GoogleTest:
    runs-on: ubuntu-latest
    container:
      image: davevader/dare_test:3.2

    strategy:
      matrix:
        procs: [1, 2, 3, 4]
        compiler: [{cc: gcc, cxx: g++, trilinos: trilinos_gcc}, {cc: clang-18, cxx: clang++-18, trilinos: trilinos_clang}]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake Test
      run: |
          rm -rf build_test
          mkdir build_test && cd build_test
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -GNinja \
                   -DUSE_GTEST=ON \
                   -DDEBUG=ON \
                   -DCMAKE_C_COMPILER=${{matrix.compiler.cc}} \
                   -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}} \
                   -DCMAKE_PREFIX_PATH=/usr/local/${{matrix.compiler.trilinos}}

    - name: Build Test
      run: |
          cd build_test
          ninja -j 4

    - name: Run Test
      run: |
          cd build_test
          mpirun -n ${{matrix.procs}} ./unit_test --gtest_output="xml:${pwd}Report_${{matrix.compiler.cc}}_P${{matrix.procs}}.xml" -t 1

    - name: Move reports
      if: always()
      run: |
          cd build_test
          mv *xml ../

    - name: Archive Testing Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test_reports_${{matrix.procs}}_${{matrix.compiler.cc}}
        path: ./*.xml

  publish-test-results:
    # For details checkout https://github.com/marketplace/actions/publish-test-results
    runs-on: ubuntu-latest
    container:
      image: davevader/dare_test:3.2
    name: Publish Tests Results
    needs: GoogleTest
    permissions:
      checks: write
      # only needed unless run with comment_mode: off
      pull-requests: write
      # only needed for private repository
      contents: read
      # only needed for private repository
      issues: read
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            artifacts/test_reports_1_gcc/*.xml
            artifacts/test_reports_2_gcc/*.xml
            artifacts/test_reports_3_gcc/*.xml
            artifacts/test_reports_4_gcc/*.xml
            artifacts/test_reports_1_clang-18/*.xml
            artifacts/test_reports_2_clang-18/*.xml
            artifacts/test_reports_3_clang-18/*.xml
            artifacts/test_reports_4_clang-18/*.xml
