name: Testing

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    
jobs:

  GoogleTest_gcc:
    runs-on: self-hosted
    container:
      image: davevader/dare_test:3.2

    strategy:
      matrix:
        procs: [1, 2, 3, 4]
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake Test
      run: |
          mkdir build_test_gcc && cd build_test_gcc
          cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja -DUSE_GTEST=ON -DDEBUG=ON

    - name: Build Test
      run: |
          cd build_test_gcc
          ninja -j 4

    - name: Run Test
      run: |
          cd build_test_gcc
          mpirun -n ${{matrix.procs}} ./unit_test --gtest_output="xml:${pwd}Report_gcc_P${{matrix.procs}}.xml" -T 1

    - name: Move reports
      if: always()
      run: |
          cd build_test_gcc
          mv *xml ../

    - name: Archive Testing Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test_reports_${{matrix.procs}}
        path: ./*.xml

  GoogleTest_clang:
    runs-on: self-hosted
    container:
      image: davevader/dare_test:3.2

    strategy:
      matrix:
        procs: [1, 2, 3, 4]
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake Test
      run: |
          mkdir build_test_clang && cd build_test_clang
          cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja -DUSE_GTEST=ON -DDEBUG=ON -DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_COMPILER=clang-18

    - name: Build Test
      run: |
          cd build_test_clang
          ninja -j 4

    - name: Run Test
      run: |
          cd build_test_clang
          mpirun -n ${{matrix.procs}} ./unit_test --gtest_output="xml:${pwd}Report_clang_P${{matrix.procs}}.xml" -T 1

    - name: Move reports
      if: always()
      run: |
          cd build_test_clang
          mv *xml ../

    - name: Archive Testing Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test_reports_${{matrix.procs}}
        path: ./*.xml

  publish-test-results:
    # For details checkout https://github.com/marketplace/actions/publish-test-results
    runs-on: self-hosted
    container:
      image: davevader/dare_test:3.2
    name: Publish Tests Results
    needs: [ GoogleTest_gcc, GoogleTest_clang]
    permissions:
      checks: write
      # only needed unless run with comment_mode: off
      pull-requests: write
      # only needed for private repository
      contents: read
      # only needed for private repository
      issues: read
    if: |
      always()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            artifacts/test_reports_1/*.xml
            artifacts/test_reports_2/*.xml
            artifacts/test_reports_3/*.xml
            artifacts/test_reports_4/*.xml
